apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: quay.io/influxdb/influxdb:2.0.0-alpha
          resources:
            limits:
              memory: "128Mi"
              cpu: "1000m"
          ports:
            - containerPort: 9999
          volumeMounts:
            - mountPath: /root/.influxdbv2
              name: influxdbv2
      volumes:
        - name: influxdbv2
          persistentVolumeClaim:
            claimName: influxdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: monitoring
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb
#    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - port: 9999
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
