apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegraf-prometheus
  template:
    metadata:
      labels:
        app: telegraf-prometheus
    spec:
      serviceAccountName: telegraf
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-prometheus
      containers:
        - name: telegraf-prometheus
          image: reckod/telegraf:watch-config
          args: ["--watch-config","on","--config","/etc/telegraf/telegraf.conf"]
          resources: {}
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
