apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-nginx-config
  namespace: default
data:
  telegraf.conf: |+
    [agent]
      interval = "10s"
      flush_interval = "10s"
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb.monitoring:9999"]
      organization = "InfluxData"
      bucket = "kubernetes"
      token = "secret-token"
    [[inputs.nginx]]
      urls = ["http://127.0.0.1/stub_status"]
    [[inputs.internal]]
      collect_memstats = true