apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-nodes
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegraf-nodes
  template:
    metadata:
      labels:
        app: telegraf-nodes
    spec:
      serviceAccountName: telegraf
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-nodes
        - name: sysro
          hostPath:
            path: /sys
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: procro
          hostPath:
            path: /proc
      containers:
        - name: telegraf-nodes
          image: reckod/telegraf:watch-config
          args: ["--watch-config","on","--config","/etc/telegraf/telegraf.conf"]
          resources: {}
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
            - name: sysro
              mountPath: /rootfs/sys
              readOnly: true
            - name: procro
              mountPath: /rootfs/proc
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: "HOST_PROC"
              value: "/rootfs/proc"
            - name: "HOST_SYS"
              value: "/rootfs/sys"
            - name: "HOST_MOUNT_PREFIX"
              value: "/rootfs"


