apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-nodes
  namespace: monitoring
data:
  telegraf.conf: |
    [agent]
      interval = "30s"
      flush_interval = "10s"
      metric_buffer_limit = 50000
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb.monitoring:9999"]
      organization = "InfluxData"
      bucket = "kubernetes"
      token = "secret-token"
    [[inputs.kubernetes]]
      url = "https://kubernetes.default.svc.cluster.local/api/v1/nodes/$NODE_NAME/proxy/"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      timeout = "5s"
      perdevice = true
      total = false
      docker_label_exclude = ["annotation.kubernetes.io/*"]
    [[inputs.cpu]]
      percpu = false
      totalcpu = true
    [[inputs.disk]]
      mount_points = ["/"]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "aufs", "squashfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.system]]
    [[inputs.net]]
    [[inputs.docker_log]]
      endpoint = "unix:///var/run/docker.sock"
      # from_beginning = false
      # container_name_include = []
      # container_name_exclude = []
      # container_state_include = []
      # container_state_exclude = []
      # docker_label_include = []
      # docker_label_exclude = []
    [[inputs.internal]]
      collect_memstats = true
