apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-control-plane
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegraf-control-plane
  template:
    metadata:
      labels:
        app: telegraf-control-plane
    spec:
      serviceAccountName: telegraf
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-control-plane
        - name: credentials
          secret:
            secretName: aws-service-user
      containers:
        - name: telegraf-control-plane
          image: reckod/telegraf:watch-config
          args: ["--watch-config","on","--config","/etc/telegraf/telegraf.conf"]
          resources: {}
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
            - name: credentials
              mountPath: /root/.aws/
              readOnly: true
          env:
            - name: EU_CENTRAL_1_1
              valueFrom:
                secretKeyRef:
                  name: eu-central-1-1
                  key: token
            - name: US_WEST_2_1
              valueFrom:
                secretKeyRef:
                  name: us-west-2-1
                  key: token

