---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consumer-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: resource-consumer
  template:
    metadata:
      labels:
        app: resource-consumer
    spec:
      containers:
        - name: resource-consumer
          image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: resource-consumer
  namespace: default
  labels:
    app: resource-consumer
spec:
  type: ClusterIP
  selector:
    app: resource-consumer
  ports:
    - name: http
      port: 8180
      targetPort: 8080
